export class FieldService {
	readonly F_SELECTED_ORDERS = 'selectedOrders';
	readonly F_IS_SELECTED_ALL = 'isSelectedAll';
	
	readonly F_ORDER_ID = 'orderId';
	readonly F_GROUP = 'group';
	readonly F_COMPANY = 'company';
	readonly F_DEPARTMENT = 'department';
	readonly F_JOB = 'job';
	readonly F_EMPLOYEE_CODE = 'employeeCode';
	readonly F_NAME = 'name';
	readonly F_AGE = 'age';
	readonly F_SEX = 'sex';
	readonly F_HEIGHT = 'height';
	readonly F_WEIGHT = 'weight';

	readonly F_SHIRT = 'shirt';
	readonly F_LONG_SLEEVES = 'longSleeves';
	readonly F_SHORT_SLEEVES = 'shortSleeves';
	readonly F_L_SLEEVE_IS_ENABLED = 'lSleeveIsEnabled';
	readonly F_S_SLEEVE_IS_ENABLED = 'sSleeveIsEnabled';

	readonly F_SUIT = 'suit';
	readonly F_TROUSERS_MODEL = 'trousersModel';
	readonly F_SKIRT_MODEL = 'skirtModel';
	readonly F_SKIRT_WAIST = 'skirtWaist';
	readonly F_SKIRT_HIP = 'skirtHip';
	readonly F_SKIRT_LENGTH = 'skirtLength';

	readonly F_COAT = 'coat';
	readonly F_WAISTCOAT = 'waistcoat';

	readonly F_ACCESSORY = 'accessory';

	readonly F_SIZENAME = 'sizeName';
	readonly F_MODEL = 'model';
	readonly F_SPEC = 'spec';
	readonly F_NECK = 'neck';
	readonly F_SHOULDER = 'shoulder';
	readonly F_FLENGTH = 'fLength';
	readonly F_BLENGTH = 'bLength';
	readonly F_CHEST = 'chest';
	readonly F_WAIST = 'waist';
	readonly F_LOWERHEM = 'lowerHem';
	readonly F_LSLEEVELENGTH = 'lSleeveLength';
	readonly F_LSLEEVECUFF = 'lSleeveCuff';
	readonly F_SSLEEVELENGTH = 'sSleeveLength';
	readonly F_SSLEEVECUFF = 'sSleeveCuff';
	readonly F_CHESTENLARGE = 'chestEnlarge';
	readonly F_WAISTENLARGE = 'waistEnlarge';
	readonly F_LOWERHEMENLARGE = 'lowerHemEnlarge';
	readonly F_PRESIZE = 'preSize';
	readonly F_PRICE = 'price';
	readonly F_LPRICE = 'lPrice';
	readonly F_SPRICE = 'sPrice';
	readonly F_MEMO = 'memo';
	readonly F_ISENABLED = 'isEnabled';
	readonly F_DETAILS = 'details';
	readonly F_SIZEDETAILS = 'sizeDetails';
	readonly F_MID_WAIST = 'midWaist';//中腰
	readonly F_SLEEVE_LENGTH = 'sleeveLength';//袖长
	readonly F_SLEEVE_CUFF = 'sleevecuff';//袖口
	readonly F_HIP = 'hip';//臀围
	readonly F_FORK = 'fork';//直档
	readonly F_WAIST_FORK = 'waistFork';//连腰直档
	readonly F_MID_FORK = 'midFork';//中档
	readonly F_LATERAL_FORK = 'lateralFork';//横档
	readonly F_TROUSERS_LENGTH = 'trousersLength';//净裤长
	readonly F_HEM_HEIGHT = 'hemHeight';//脚口
	readonly F_WOMAN_WAIST = 'womanWaist';//腰成

	readonly F_SUBCATEGORY = 'subCategory';
	readonly F_AMOUNT = 'amount';
	readonly F_COLOR = 'color';
	readonly F_CLOTH = 'cloth';

	readonly F_SIZE_ID = 'sizeId';
	readonly F_SIZE_TABLE_NAME = 'sizeTableName';
	readonly F_CATEGOTY = 'category';
	readonly F_SIZE_ALIAS = "sizeAlias"; 
	readonly F_NECK_SCOPE_L = "neckScopeL";
	readonly F_NECK_SCOPE_U = "neckScopeU";
	readonly F_SHOULDER_SCOPE_L = "shoulderScopeL";
	readonly F_SHOULDER_SCOPE_U = "shoulderScopeU";
	readonly F_FLENGTH_SCOPE_L = "fLengthScopeL";
	readonly F_FLENGTH_SCOPE_U = "fLengthScopeU";
	readonly F_BLENGTH_SCOPE_L = "bLengthScopeL";
	readonly F_BLENGTH_SCOPE_U = "bLengthScopeU";
	readonly F_CHEST_SCOPE_L = "chestScopeL";
	readonly F_CHEST_SCOPE_U = "chestScopeU";
	readonly F_WAIST_SCOPE_L = "waistScopeL";
	readonly F_WAIST_SCOPE_U = "waistScopeU";
	readonly F_LOWERHEM_SCOPE_L = "lowerHemScopeL";
	readonly F_LOWERHEM_SCOPE_U = "lowerHemScopeU";
	readonly F_LSLEEVE_LENGTH_SCOPE_L = "lSleeveLengthScopeL";
	readonly F_LSLEEVE_LENGTH_SCOPE_U = "lSleeveLengthScopeU";
	readonly F_LSLEEVE_CUFF_SCOPE_L = "lSleeveCuffScopeL";
	readonly F_LSLEEVE_CUFF_SCOPE_U = "lSleeveCuffScopeU";
	readonly F_SSLEEVE_LENGTH_SCOPE_L = "sSleeveLengthScopeL";
	readonly F_SSLEEVE_LENGTH_SCOPE_U = "sSleeveLengthScopeU";
	readonly F_SSLEEVE_CUFF_SCOPE_L = "sSleeveCuffScopeL";
	readonly F_SSLEEVE_CUFF_SCOPE_U = "sSleeveCuffScopeU";
	readonly F_IS_LOCKED = "isLocked";

	readonly F_FLENGTH_VAR = 'fLengthVar';
	readonly F_BLENGTH_VAR = 'bLengthVar';
	readonly F_SLEEVE_LENGTH_VAR = 'sleeveLengthVar';
	readonly F_SHOULDER_VAR = 'shoulderVar';
	readonly F_CHEST_VAR = 'chestVar';
	readonly F_MID_WAIST_VAR = 'midWaistVar';
	readonly F_LOWERHEM_VAR = 'lowerhemVar';
	readonly F_SLEEVE_CUFF_VAR = 'sleeveCuffVar';
	readonly F_WAIST_VAR = 'waistVar';
	readonly F_HIP_VAR = 'hipVar';
	readonly F_WAIST_FORK_VAR = 'waistForkVar';
	readonly F_LATERAL_FORK_VAR = 'lateralForkVar';
	readonly F_TROUSERS_LENGTH_VAR = 'trousersLengthVar';
	readonly F_HEM_HEIGHT_VAR = 'hemHeightVar';
	readonly F_WOMAN_WAIST_VAR = 'womanWaistVar';
	readonly F_FORK_VAR = 'forkVar';
	readonly F_MID_FORK_VAR = 'midForkVar';
	readonly F_SKIRT_WAIST_VAR = 'skirtWaistVar';
	readonly F_SKIRT_HIP_VAR = 'skirtHipVar';
	readonly F_SKIRT_LENGTH_VAR = 'skirtLengthVar';

	readonly F_USER_ID = 'userId';
	readonly F_USERNAME = 'username';
	readonly F_PASSWORD = 'password';
	readonly F_CONFIRM_PASSWORD = 'confirmPassword';
	readonly F_USER_TYPE_ID = 'userTypeId';

	readonly F_OLD_PASSWORD = 'oldPassword';
	readonly F_NEW_PASSWORD = 'newPassword';

	readonly F_MAN_SIZE_ID = 'manSizeId';
	readonly F_WOMAN_SIZE_ID = 'womanSizeId';

	readonly COMPANY = '公司名称';
	readonly GROUP = '集团名称';
	readonly DEPARTMENT = '部门';
	readonly NAME = '姓名';
	readonly EMPLOYEE_CODE = '工号';
	readonly AGE = '年龄';
	readonly HEIGHT = '身高';
	readonly WEIGHT = '体重';
	readonly AMOUNT = '数量';
	readonly COLOR = '颜色';
	readonly CLOTH = '布料';
	readonly CATEGORY = '分类';
	readonly SUB_CATEGORY = '种类';
	readonly SIZENAME = '尺码';
	readonly SIZE_TABLE_NAME = '尺码表名称';
	readonly PRICE = '加工费';
	readonly MODEL = '号型';
	readonly SPEC = '规格';
	readonly CHEST = '胸围';
	readonly WAIST = '腰围';
	readonly NECK = '领围';
	readonly SHOULDER = '肩宽';
	readonly F_LENGTH = '前衣长';
	readonly B_LENGTH = '后衣长';
	readonly L_SLEEVE = '长袖';
	readonly L_SLEEVE_LENGTH = '长袖长';
	readonly L_SLEEVE_CUFF = '长袖口大';
	readonly L_PRICE = '长袖加工费';
	readonly S_SLEEVE = '短袖';
	readonly S_SLEEVE_LENGTH = '短袖长';
	readonly S_SLEEVE_CUFF = '短袖口大';
	readonly S_PRICE = '短袖加工费';
	readonly LOWER_HEM = '下摆';
	readonly CHEST_ENLARGE = '胸围放大';
	readonly WAIST_ENLARGE = '腰围放大';
	readonly LOWER_HEM_ENLARGE = '下摆放大';
	readonly MID_WAIST = '中腰';
	readonly SLEEVE_LENGTH = '袖长';
	readonly SLEEVE_CUFF = '袖口';
	readonly HIP = '臀围';
	readonly FORK = '直档';
	readonly WAIST_FORK = '连腰直档';
	readonly MID_FORK = '中档';
	readonly LATERAL_FORK = '横档';
	readonly TROUSERS_LENGTH = '净裤长';
	readonly HEM_HEIGHT = '脚口';
	readonly SKIRT_MODEL = '裙号型';
	readonly SKIRT_WAIST = '裙腰围';
	readonly SKIRT_HIP = '裙臀围';
	readonly SKIRT_LENGTH = '裙长';
	readonly WOMAN_WAIST = '腰成';

	readonly T_SHIRT = 'T恤';
	readonly ACCESSORY = '配件';
	readonly SUIT = '西服';
	readonly COAT = '大衣';
	readonly WAISTCOAT = '背心';

	readonly FLENGTH_VAR = '前衣长变量';
	readonly BLENGTH_VAR = '后衣长变量';
	readonly SLEEVE_LENGTH_VAR = '袖长变量';
	readonly SHOULDER_VAR = '肩宽变量';
	readonly CHEST_VAR = '胸围变量';
	readonly MID_WAIST_VAR = '中腰变量';
	readonly LOWERHEM_VAR = '下摆变量';
	readonly SLEEVE_CUFF_VAR = '袖口变量';
	readonly WAIST_VAR = '腰围变量';
	readonly HIP_VAR = '臀围变量';
	readonly WAIST_FORK_VAR = '连腰直档变量';
	readonly LATERAL_FORK_VAR = '横档变量';
	readonly TROUSERS_LENGTH_VAR = '净裤长变量';
	readonly HEM_HEIGHT_VAR = '脚口变量';
	readonly WOMAN_WAIST_VAR = '腰成变量';
	readonly FORK_VAR = '直档变量';
	readonly MID_FORK_VAR = '中档变量';
	readonly SKIRT_WAIST_VAR = '裙腰围变量';
	readonly SKIRT_HIP_VAR = '裙臀围变量';
	readonly SKIRT_LENGTH_VAR = '裙长变量';

	readonly SIZE_ALIAS = '尺码别名';
	readonly NECK_SCOPE_L = '领围下限';
	readonly NECK_SCOPE_U='领围上限';
	readonly SHOULDER_SCOPE_L='肩宽下限';
	readonly SHOULDER_SCOPE_U='肩宽上限';
	readonly FLENGTH_SCOPE_L='前衣长下限';
	readonly FLENGTH_SCOPE_U='前衣长上限';
	readonly BLENGTH_SCOPE_L='后衣长下限';
	readonly BLENGTH_SCOPE_U = '后衣长上限';
	readonly CHEST_SCOPE_L = '胸围下限';
	readonly CHEST_SCOPE_U = '胸围上限';
	readonly WAIST_SCOPE_L = '腰围下限';
	readonly WAIST_SCOPE_U = '腰围上限';
	readonly LOWERHEM_SCOPE_L = '下摆下限';
	readonly LOWERHEM_SCOPE_U = '下摆上限';
	readonly LSLEEVE_LENGTH_SCOPE_L = '长袖长下限';
	readonly LSLEEVE_LENGTH_SCOPE_U = '长袖长上限';
	readonly LSLEEVE_CUFF_SCOPE_L = '长袖口大下限';
	readonly LSLEEVE_CUFF_SCOPE_U = '长袖口大上限';
	readonly SSLEEVE_LENGTH_SCOPE_L = '短袖长下限';
	readonly SSLEEVE_LENGTH_SCOPE_U = '短袖长上限';
	readonly SSLEEVE_CUFF_SCOPE_L = '短袖口大下限';
	readonly SSLEEVE_CUFF_SCOPE_U = '短袖口大上限';

	readonly MAN_SIZE = '男装尺码';
	readonly WOMAN_SIZE = '女装尺码';
}
